In [1]:
from synaptronix import *

NN = Synaptronix(inputs_size = 3, outputs_size = 5)

NN.add_multiple_layers(2)
NN.add_multiple_layers(5)
NN.add_batch_nodes(5)
NN.f_propagate(np.array([10, 20, 15]))

Initial weights created with value [0.873]
Node created
Initial weights created with value [0.493]
Node created
Initial weights created with value [0.98]
Node created
Multiple nodes created (3) with number of entry equal to [1.]
Initial weights created with value [0.766 0.681 0.203]
Node created
Initial weights created with value [0.721 0.418 0.195]
Node created
Initial weights created with value [0.887 0.074 0.588]
Node created
Initial weights created with value [0.087 0.232 0.733]
Node created
Initial weights created with value [0.654 0.172 0.307]
Node created
Multiple nodes created (5) with number of entry equal to [1. 1. 1.]
Neural Network created
New layer added
New layer added
Initial weights created with value []
Node created
Initial weights created with value []
Node created
Initial weights created with value []
Node created
Initial weights created with value []
Node created
Initial weights created with value []
Node created
Multiple nodes created (5) with number of entry equal

In [2]:
NN = Synaptronix(inputs_size = 3, outputs_size = 5)
NN.add_multiple_layers(2)
NN.add_multiple_layers(5)
NN.add_batch_nodes(5)

Initial weights created with value [0.048]
Node created
Initial weights created with value [0.944]
Node created
Initial weights created with value [0.475]
Node created
Multiple nodes created (3) with number of entry equal to [1.]
Initial weights created with value [0.248 0.969 0.794]
Node created
Initial weights created with value [0.746 0.563 0.98 ]
Node created
Initial weights created with value [0.505 0.838 0.815]
Node created
Initial weights created with value [0.839 0.931 0.447]
Node created
Initial weights created with value [0.285 0.161 0.613]
Node created
Multiple nodes created (5) with number of entry equal to [1. 1. 1.]
Neural Network created
New layer added
New layer added
Initial weights created with value []
Node created
Initial weights created with value []
Node created
Initial weights created with value []
Node created
Initial weights created with value []
Node created
Initial weights created with value []
Node created
Multiple nodes created (5) with number of entry equa

In [3]:
x = np.array([[[10, 20, 15], [5, 10, -2]]])

In [4]:
NN.fit(x)

Initial weights created with value [0.089]
Node created
Initial weights created with value [0.93]
Node created
Initial weights created with value [0.968]
Node created
Layer inputs updated
Node inputs updated
--- Calculate node ---
1
[0.778 0.804 0.992]
[10. 20. 15.]
--- Calculate node ---
Weighted output calculated, with final value of  38.74
Node inputs updated
--- Calculate node ---
1
[0.026 0.683 0.566]
[10. 20. 15.]
--- Calculate node ---
Weighted output calculated, with final value of  22.409999999999997
Node inputs updated
--- Calculate node ---
1
[0.943 0.678 0.756]
[10. 20. 15.]
--- Calculate node ---
Weighted output calculated, with final value of  34.33
Node inputs updated
--- Calculate node ---
1
[0.128 0.955 0.634]
[10. 20. 15.]
--- Calculate node ---
Weighted output calculated, with final value of  29.89
Node inputs updated
--- Calculate node ---
1
[0.26  0.616 0.401]
[10. 20. 15.]
--- Calculate node ---
Weighted output calculated, with final value of  20.935000000000002
[

In [35]:
x = np.array([1710.85267596, 2080.72352487, 1747.51755317, 1473.5250187,  1645.16038217])

w = np.array([[0.052, 0.249, 0.756, 0.128, 0.746], [0.559, 0.898, 0.932, 0.983, 0.199], [0.301, 0.497, 0.95,  0.725, 0.868], [0.671, 0.639, 0.592, 0.72,  0.058], [0.736, 0.351, 0.51,  0.305, 0.103]])

iterator = 0

for array in w:
    print(f'Node {iterator}')
    #print(x * w)
    print(sum(x * array))
    iterator += 1


Node 0
3344.08861453149
Node 1
6229.4047401832695
Node 2
5705.532773116909
Node 3
4668.45218506759
Node 4
3499.6321289196403


In [17]:
'''
# --- Inputs ---

7 [1710.85267596 2080.72352487 1747.51755317 1473.5250187  1645.16038217]

# --- Weights ---



# --- Outputs ---

-1 [3344.08861453 6229.40474019 5705.53277312 4668.45218507 3499.63212892]

'''

[15.97029 14.8608  13.52574  2.07045  8.65879]
55.08607000000001


In [5]:
for layer in NN.layers:
    node_id = 0
    print('-----New Layer-----')
    print(layer.layer_id, layer.nodes_outputs)
    for node in layer.nodes:
        print(node_id, node.weights)
        node_id += 1
    print('-----End Layer-----')

-----New Layer-----
0 [ 5. 10. -2.]
0 [1.]
1 [1.]
2 [1.]
-----End Layer-----
-----New Layer-----
1 [9.946 5.828 9.983 8.922 6.658]
0 [0.778 0.804 0.992]
1 [0.026 0.683 0.566]
2 [0.943 0.678 0.756]
3 [0.128 0.955 0.634]
4 [0.26  0.616 0.401]
-----End Layer-----
-----New Layer-----
2 [22.40375  17.519987 23.205809 22.168414 20.496395]
0 [0.784 0.089 0.182 0.691 0.917]
1 [0.522 0.586 0.005 0.674 0.428]
2 [0.172 0.909 0.679 0.649 0.545]
3 [0.949 0.377 0.148 0.5   0.69 ]
4 [0.971 0.061 0.115 0.812 0.314]
-----End Layer-----
-----New Layer-----
3 [63.80841264 77.18362483 28.85014818 32.45958763 44.52124396]
0 [0.996 0.609 0.293 0.566 0.56 ]
1 [0.641 0.674 0.797 0.804 0.717]
2 [0.502 0.246 0.14  0.148 0.33 ]
3 [0.394 0.824 0.027 0.087 0.324]
4 [0.467 0.415 0.309 0.222 0.717]
-----End Layer-----
-----New Layer-----
4 [122.71093876  94.16885658 116.03752812 101.99895146  29.18646865]
0 [0.131 0.757 0.908 0.252 0.484]
1 [0.151 0.51  0.559 0.187 0.516]
2 [0.573 0.168 0.111 0.816 0.827]
3 [0.18  0